name: '[Scraper] Run Every 6 Hours'

on:
  schedule:
    - cron: '0 */6 * * *' # Runs at 00:00, 06:00, 12:00, 18:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Scraper
        run: python final_scraper.py

      - name: Commit data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add fujairah_plates_data.csv
          git commit -m "Update plate data (6-hour schedule)" || exit 0
          git push

      - name: Check for Hourly Trigger
        if: success() && file.exists('trigger_hourly.txt')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Last day detected. Switching to hourly workflow."
          gh workflow disable every-6-hours.yml
          gh workflow enable every-hour.yml
