name: '[Scraper] Run Every Hour'

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Run Scraper
        run: python final_scraper.py

      - name: Commit data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add fujairah_plates_data.csv
          git commit -m "Update plate data (Hourly schedule)" || exit 0
          git push

      # --- CORRECTED BLOCK ---
      - name: Check and Trigger 3-Minute Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f "trigger_3_minutes.txt" ]; then
            echo "Final 30 minutes detected. Switching to 3-minute workflow."
            gh workflow disable 'every-hour.yml'
            gh workflow enable 'every-3-minutes.yml'
          else
            echo "Not in the final 30 minutes yet."
          fi
